# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_auto_20170811_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='startup_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='startup',
            name='statrup_email',
            field=models.CharField(max_length=30),
        ),
    ]
