# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-11 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_auto_20170811_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='startup_blurb',
            new_name='blurb',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='startup_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='statrup_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='startup_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='startup_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='startup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 11, 23, 35, 52, 261974, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
