# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.4 on 2017-08-11 03:48
=======
# Generated by Django 1.9.4 on 2017-08-11 02:48
>>>>>>> fbf95131af2065fb59ae9c52aacc52e1cc54aeb0
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=20)),
                ('statrup_email', models.CharField(max_length=20)),
                ('startup_logo', models.FileField(upload_to='')),
                ('startup_description', models.TextField()),
            ],
        ),
    ]
