# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-11 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='startup_blurb',
            field=models.TextField(default='Max character count: 150', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startup_name',
            field=models.CharField(max_length=10),
        ),
    ]
