# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-11 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('profile_img', models.FileField(upload_to='')),
                ('user_blurb', models.TextField(max_length=150)),
            ],
        ),
    ]
