# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-13 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170812_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
